### ISSUE TITLE
Uncaught Error: /bin/sh: -c: line 0: syntax error near unexpected token `('/bin/sh: -c: line 0: ...

### ISSUE THREAD

**Issue by vith** [coopermaruyama/atom-git-wip#11]
Just got this when saving a file.

**Atom Version**: 1.0.19
**System**: "Arch Linux"
**Thrown From**: [git-wip](https://github.com/coopermaruyama/atom-git-wip) package, v0.1.3
### Stack Trace

```
Uncaught Error: /bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `git wip save "Atom autosave: /home/vith/code/modern-scroll/Chromium (.crx)/manifest.json" --editor -- /home/vith/code/modern-scroll/Chromium (.crx)/manifest.json'
```

```
At /home/vith/.dotfiles/atom/packages/git-wip/lib/git-wip.coffee:93

Error: /bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `git wip save "Atom autosave: /home/vith/code/modern-scroll/Chromium (.crx)/manifest.json" --editor -- /home/vith/code/modern-scroll/Chromium (.crx)/manifest.json'

  at /home/vith/.dotfiles/atom/packages/git-wip/lib/git-wip.coffee:93:23
  at /home/vith/.dotfiles/atom/packages/git-wip/node_modules/shelljs/src/exec.js:142:7
  at ChildProcess.exithandler (child_process.js:215:5)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:764:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
  2x -0:11.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  4x -0:10.4.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:00.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-pair",
      "firepad",
      "motepair",
      "supercopair",
      "nuclide-file-tree",
      "autocomplete-plus-python-jedi",
      "python-jedi",
      "symbols-view",
      "project-view",
      "remote-sync"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Stylus, v1.2.1
aligner, v0.17.0
atom-ternjs, v0.8.4
autocomplete-modules, v1.3.0
autocomplete-python, v0.6.3
color-picker, v2.0.13
cursor-history, v0.5.4
file-icon-supplement, v0.8.3
file-icons, v1.6.10
git-wip, v0.1.3
go-plus, v3.5.1
language-babel, v0.15.7
language-diff, v0.3.1
language-lua, v0.9.4
linter, v1.8.1
linter-eslint, v3.1.1
linter-python-pep8, v0.2.0
linter-shellcheck, v1.0.2
linter-stylint, v2.0.1
markdown-preview-plus, v2.2.2
minimap, v4.13.4
minimap-linter, v1.0.0
package-sync, v0.2.0
pigments, v0.18.0
project-ring, v0.35.2
python-autopep8, v0.1.3
python-tools, v0.6.5
symbols-tree-view, v0.10.0

# Dev
No dev packages
```

**Comment by czxtm** [comment]
Ah, looks like this is due to the space in the filename. I've pushed a new version which adds quotes around the filename, should solve this. Let me know if it happens again.

Thanks!
