### ISSUE TITLE
Uncaught Error: fatal: ... is outside repository Cannot save the current worktree state.

### ISSUE THREAD

**Issue by athompson-r7** [coopermaruyama/atom-git-wip#13]
1. This is happening fairly regularly on file save.

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [git-wip](https://github.com/coopermaruyama/atom-git-wip) package, v0.3.0
### Stack Trace

Uncaught Error: fatal: /Users/athompson/code/daemon_runner-add-retry/lib/daemon_runner/retry_errors.rb: '/Users/athompson/code/daemon_runner-add-retry/lib/daemon_runner/retry_errors.rb' is outside repository
Cannot save the current worktree state.

```
At /Users/athompson/.atom/packages/git-wip/lib/git-wip.coffee:133

Error: fatal: /Users/athompson/code/daemon_runner-add-retry/lib/daemon_runner/retry_errors.rb: '/Users/athompson/code/daemon_runner-add-retry/lib/daemon_runner/retry_errors.rb' is outside repository
Cannot save the current worktree state.

    at /Users/athompson/.atom/packages/git-wip/lib/git-wip.coffee:133:23
    at /Users/athompson/.atom/packages/git-wip/node_modules/shelljs/src/exec.js:142:7
    at ChildProcess.exithandler (child_process.js:221:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```
### Commands

```
     -0:02.6.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:01.3.0 vim-mode:delete (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.4.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "ruby-quick-test",
      "linter-foodcritic",
      "git-wip"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
achievements, v0.9.0 (active)
atom-html-preview, v0.1.22 (active)
atom-runner, v2.7.1 (inactive)
auto-copyright, v0.5.0 (inactive)
auto-detect-indentation, v1.3.0 (active)
autocomplete, v0.47.0 (inactive)
autocomplete-ruby, v0.2.1 (active)
editorconfig, v1.6.0 (active)
git-log, v0.4.1 (active)
git-plus, v5.18.0 (active)
git-wip, v0.3.0 (inactive)
language-chef, v0.9.0 (active)
language-groovy, v0.6.0 (active)
linter, v1.11.18 (active)
linter-foodcritic, v0.5.2 (inactive)
linter-rubocop, v0.5.0 (active)
markdown-writer, v2.6.1 (inactive)
minimap, v4.25.6 (active)
minimap-find-and-replace, v4.5.1 (active)
react, v0.16.1 (active)
rubocop-auto-correct, v1.5.1 (inactive)
ruby-quick-test, v0.4.0 (inactive)
ruby-test, v0.9.17 (inactive)
todo-show, v1.7.0 (inactive)
toggle-quotes, v1.0.0 (inactive)
vim-mode, v0.65.1 (active)
yard, v0.3.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (active)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by czxtm** [comment]
Hi, thanks for opening this. This won't be easy to debug since it's being thrown from a package that this package depends on (shelljs) so I'll need to ask a favor from you. can you do the following please:
1. Open a different project and check if it happens there. Let me know if it's only happening on one project or all your projects.
2. Get this error to happen again, then right after, open the atom developer console (cmd + alt + i ) then type the following.:

```
gitWip = atom.packages.getActivePackage('git-wip').mainModule
gitWip.getDebugLog()
```

This will print out some debug info internal to this package. copy/paste that for me here.

Thanks

**Comment by czxtm** [comment]
Doing some more investigating, it looks like the error message is coming from git-wip (the shell script used in this package) on this line here: https://github.com/bartman/git-wip/blob/master/git-wip#L199

My intuition is that maybe the state of your git working tree is not in a state where git-wip can do its thing. Maybe you are in the middle of a merge or something. If this is the case then it will probably fail only on the specific project where this error happened. Let me know if this is the case.

**Comment by czxtm** [comment]
closing due to inactivity
