### ISSUE TITLE
Uncaught Error: error: Ref refs/wip/DM-5695-migrate-sheet-to-yml is at 7e3b031eaba3fda06261e51eae...

### ISSUE THREAD

**Issue by abhayn-webonise** [coopermaruyama/atom-git-wip#14]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Ubuntu 14.04.1
**Thrown From**: [git-wip](https://github.com/coopermaruyama/atom-git-wip) package 0.3.0

### Stack Trace

Uncaught Error: error: Ref refs/wip/DM-5695-migrate-sheet-to-yml is at 7e3b031eaba3fda06261e51eae132271adf4b0df but expected 136de1281f570d22583f19488dcb732466bdda52
fatal: Cannot lock the ref 'refs/wip/DM-5695-migrate-sheet-to-yml'.

```
At /home/webonise/.atom/packages/git-wip/lib/git-wip.coffee:133

Error: error: Ref refs/wip/DM-5695-migrate-sheet-to-yml is at 7e3b031eaba3fda06261e51eae132271adf4b0df but expected 136de1281f570d22583f19488dcb732466bdda52
fatal: Cannot lock the ref 'refs/wip/DM-5695-migrate-sheet-to-yml'.

    at /packages/git-wip/lib/git-wip.coffee:133:23
    at /packages/git-wip/node_modules/shelljs/src/exec.js:142:7
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
 10x -6:28.6.0 core:save (input.hidden-input)
     -5:55.8.0 application:open-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:52.5.0 application:add-project-folder (input.hidden-input)
     -5:27.6.0 core:save (input.hidden-input)
     -5:25 core:backspace (input.hidden-input)
  2x -5:24.5.0 core:save (input.hidden-input)
     -5:16.5.0 core:undo (input.hidden-input)
  3x -5:15.9.0 core:save (input.hidden-input)
     -4:31.4.0 core:backspace (input.hidden-input)
     -4:22.8.0 core:save (input.hidden-input)
     -3:57.5.0 tree-view:remove-project-folder (span.name.icon.icon-repo)
  2x -3:45.5.0 core:undo (input.hidden-input)
     -3:44.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-css-comb 3.1.0 
atom-react-autocomplete 0.1.10 
atom-react-native-autocomplete 0.0.27 
atom-react-native-css 1.1.3 
atom-react-preview 2.0.0 
atomic-chrome 0.3.0 
autocomplete-ruby 0.1.0 
badass-react-snippets 1.0.0 
cucumber 0.6.0 
cucumber-step 0.2.0 
egghead-react-snippets 1.2.2 
git-blame 0.4.12 
git-checkout 0.3.2 
git-commit 1.5.3 
git-control 0.8.2 
git-diff-details 1.3.0 
git-gui 0.1.24 
git-line 0.5.0 
git-log 0.4.1 
git-plus 5.17.1 
git-status 0.3.4 
git-time-machine 1.5.3 
git-tools 0.4.1 
git-wip 0.3.0 
language-docker 1.1.7 
language-haml 0.24.1 
language-javascript-jsx 0.3.7 
language-rspec 0.5.1 
linter 1.11.23 
linter-codeclimate 0.1.2 
linter-haml 2.0.0 
linter-rubocop 1.1.0 
linter-ruby 1.2.5 
react 0.16.0 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.9 
react-native-snippets 0.3.0 
react-redux-atom-snippets 0.1.1 
react-snippets 0.4.2 
ruby-slim 0.2.0 
ruby-test 1.0.1 
source-preview-react 0.2.0 
Sublime-Style-Column-Selection 1.7.3 
tabs-to-spaces 1.0.2 
toggle-quotes 1.0.1 
trailing-spaces 0.4.0 
vim-mode 0.65.1 
```

**Comment by czxtm** [comment]
I'm almost certain this is due to an issue in the state of your git working tree. This issue has come up before, try running `git update-ref -d refs/wip/master` and see if it fixes it.
