### ISSUE TITLE
Failed to activate the git-wip package

### ISSUE THREAD

**Issue by matthijsotterloo** [coopermaruyama/atom-git-wip#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.11
**Thrown From**: [git-wip](https://github.com/coopermaruyama/atom-git-wip) package, v0.1.1
### Stack Trace

Failed to activate the git-wip package

```
At editor is not defined

ReferenceError: editor is not defined
  at Object.module.exports.GitWip.activate (/Users/matthijsotterloo/.atom/packages/git-wip/lib/git-wip.coffee:30:7)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:641:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:96:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.1
git-diff-details, v0.18.0
git-projects, v1.14.1
git-wip, v0.1.1
language-sql-mysql, v0.3.1
my-github-profile, v0.2.0
remote-edit, v1.8.2
remote-sync, v3.1.2
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by g13013** [comment]
temporary workarround, edit `~/Users/aboubakr/.atom/packages/git-wip/keymaps/git-wip.cson`
and add the missing `'` caracter at the end of line 12

or replace with the following content:

``` cson
# Keybindings require three things to be fully defined: A selector that is
# matched against the focused element, the keystroke and the command to
# execute.
#
# Below is a basic keybinding which registers on all platforms by applying to
# the root workspace element.

# For more detailed documentation see
# https://atom.io/docs/latest/behind-atom-keymaps-in-depth
'atom-workspace':
  'alt-g w': 'git-wip:add-file-checkpoint'
  'alt-cmd-g w': 'git-wip:add-project-checkpoint'

```

**Comment by czxtm** [comment]
oops, I already fixed this but I guess it never published.. 😡

I'll push this asap.

**Comment by matthijsotterloo** [comment]
Ahh great! Thanks :)

2015-07-06 22:07 GMT+02:00 Cooper Maruyama notifications@github.com:

**Comment by czxtm** [comment]
Pushed, and also fixed a few more things. It's been a while since I last worked on this so please let me know of any new errors. Closing for now.
