### ISSUE TITLE
Uncaught TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by Ramesh009** [coopermaruyama/atom-git-wip#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.178.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [git-wip](https://github.com/coopermaruyama/atom-git-wip) package, v0.1.3
### Stack Trace

Uncaught TypeError: Cannot read property 'bind' of undefined

```
At E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\src\pane.js:782

TypeError: Cannot read property 'bind' of undefined
  at Object.module.exports.GitWip.getRepos (C:\Users\kkdaadhi\.atom\packages\git-wip\lib\git-wip.coffee:51:86)
  at Object.module.exports.GitWip.getWorkingDirectories (C:\Users\kkdaadhi\.atom\packages\git-wip\lib\git-wip.coffee:54:6)
  at Object.module.exports.GitWip.doGitWip (C:\Users\kkdaadhi\.atom\packages\git-wip\lib\git-wip.coffee:71:6)
  at C:\Users\kkdaadhi\.atom\packages\git-wip\lib\git-wip.coffee:31:12
  at Emitter.module.exports.Emitter.emit (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\node_modules\service-hub\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.saveAs (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\node_modules\text-buffer\lib\text-buffer.js:974:20)
  at TextBuffer.module.exports.TextBuffer.save (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\node_modules\text-buffer\lib\text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\src\text-editor.js:620:26)
  at Pane.module.exports.Pane.saveItem (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\src\pane.js:542:18)
  at Pane.module.exports.Pane.saveActiveItem (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\src\pane.js:525:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\src\workspace.js:679:35)
  at atom-workspace.atom.commands.add.core:save (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\src\workspace-element.js:295:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\src\command-registry.js:243:29)
  at E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (E:\Kiran\Applications\PortableApps\atom-windows\Atom\resources\app\src\window-event-handler.js:172:20)

```
### Commands

```
     -32:43.4 core:move-up (atom-text-editor.editor)
 21x -32:43.0 core:move-right (atom-text-editor.editor)
 60x -32:40.0 core:select-left (atom-text-editor.editor)
     -32:35.3 core:copy (atom-text-editor.editor)
     -32:35.1 core:move-down (atom-text-editor.editor)
  9x -32:34.6 core:move-right (atom-text-editor.editor)
 25x -32:32.6 core:select-left (atom-text-editor.editor)
     -32:29.1 core:paste (atom-text-editor.editor)
 60x -32:28.4 core:move-left (atom-text-editor.editor)
 64x -32:23.3 core:move-right (atom-text-editor.editor)
     -32:18.1 core:delete (atom-text-editor.editor)
  2x -32:15.9 core:save (atom-text-editor.editor)
     -31:09.3 core:backspace (atom-text-editor.editor.mini)
     -30:55.0 core:save (atom-text-editor.editor)
  7x -30:37.4 core:backspace (atom-text-editor.editor.mini)
     -30:13.0 core:save (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "tualo-git-context",
      "vim-mode",
      "minimap",
      "minimap-git-diff",
      "tree-view-git-status",
      "git-wip",
      "atomatigit"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
blame, v0.1.2
color-picker, v2.0.10
git-control, v0.3.0
git-go, v1.0.1
git-log, v0.4.1
git-plus, v5.2.2
import, v1.3.0
pigments, v0.8.4
travis-ci-status, v0.16.0
tree-view-git-modified, v0.5.10
tree-view-git-projects, v0.5.0

# Dev
No dev packages
```

**Comment by czxtm** [comment]
Hi, it looks like you're using a pretty old version of atom (0.178.0), which is pre-1.0 and does not have the `repositoryForDirectory` implemented yet. This error should go away once you update atom. Please let me know if you still get this error after updating, and re-open this issue.
