### ISSUE TITLE
Uncaught Error: error: Ref refs/wip/loop-payloads is at 300c844b9fb758284bc08d4d7a9374d358c9d425 ...

### ISSUE THREAD

**Issue by SlimeQ** [coopermaruyama/atom-git-wip#9]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: elementary OS
**Thrown From**: [git-wip](https://github.com/coopermaruyama/atom-git-wip) package, v0.1.3
### Stack Trace

Uncaught Error: error: Ref refs/wip/loop-payloads is at 300c844b9fb758284bc08d4d7a9374d358c9d425 but expected 6b1b434c2788dc6919739c66c1b1351eba901631
fatal: Cannot lock the ref 'refs/wip/loop-payloads'.

```
At /home/quincy/.atom/packages/git-wip/lib/git-wip.coffee:93

Error: error: Ref refs/wip/loop-payloads is at 300c844b9fb758284bc08d4d7a9374d358c9d425 but expected 6b1b434c2788dc6919739c66c1b1351eba901631
fatal: Cannot lock the ref 'refs/wip/loop-payloads'.

  at /home/quincy/.atom/packages/git-wip/lib/git-wip.coffee:93:23
  at /home/quincy/.atom/packages/git-wip/node_modules/shelljs/src/exec.js:142:7
  at ChildProcess.exithandler (child_process.js:720:7)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
 22x -4:25.8.0 core:move-left (atom-text-editor.editor.is-focused)
  7x -4:18.6.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:17.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:17 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -4:16.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:14.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:11.5.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:11.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -3:29.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:47.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.5.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -0:15.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.9.0 git-plus:menu (atom-text-editor.editor.is-focused)
     -0:12.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "nuclide-file-tree",
      "hyperclick",
      "nuclide-arcanist",
      "nuclide-code-format",
      "nuclide-diagnostics-store",
      "nuclide-diagnostics-ui",
      "nuclide-diff-view",
      "nuclide-file-watcher",
      "nuclide-find-references",
      "nuclide-flow",
      "nuclide-hack",
      "nuclide-hg-repository",
      "nuclide-installer",
      "nuclide-language-hack",
      "nuclide-ocaml",
      "nuclide-quick-open",
      "nuclide-remote-projects",
      "nuclide-type-hint",
      "tree-view-git-modified"
    ],
    "packagesWithKeymapsDisabled": [
      "nuclide-file-tree"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Remote-FTP, v0.7.2
Sublime-Style-Column-Selection, v1.3.0
browser-plus, v0.0.34
chary-tree-view, v0.2.3
debugger, v0.0.1
editor-stats, v0.17.0
git-log, v0.4.1
git-plus, v5.4.7
git-wip, v0.1.3
java-importer, v1.4.0
language-ejs, v0.2.0
language-gradle, v0.0.3
language-salesforce, v0.6.0
linter-coffeescript, v1.0.0
markdown-preview-plus, v2.0.1
project-manager, v2.4.0
set-syntax, v0.3.0
tabs-to-spaces, v0.11.1
tidy-tabs, v0.2.0
tree-view-git-branch, v0.0.2
tree-view-git-projects, v0.5.0
tree-view-git-status, v0.1.2

# Dev
No dev packages
```

**Comment by czxtm** [comment]
Going to merge with #10 as the errors are similar.
